#!/bin/sh
echo -e "\033[31;3m██████████████████████████████████████████████████████████████████████████████\n"
echo -e "\033[31;3mTHIS IS A NOTICE OF MONITORING OF THE FREIGHT TRUST NETWORK (FTN) INFORMATION SYSTEMS"
echo -e "\033[31;3m██████████████████████████████████████████████████████████████████████████████\n"
sleep 1
echo -e "\033[33;3mThis BLOCKCHAIN system, including all related equipment, networks, and "
echo -e "\033[33;3mnetwork devices (including Internet access), is provided by FreightTrust "
echo -e "\033[33;3mand Clearing Corporation in accordance with the rulebook and/or policies "
echo -e "\033[33;3msetforth in the "Omnibus Documentation" and/or "Rulebook". This network "
echo -e "\033[33;3mis for official (i.e."business") use and limited personal use. "
echo -e "\n"
echo -e "\033[33;3mAll FTN computer systems may be monitored for all lawful purposes, "
echo -e "\033[33;3mincluding but not limited to, ensuring that use is authorized, for "
echo -e "\033[33;3mmanagement of the system, to facilitate protection against "
echo -e "\033[33;3munauthorized access, and to verify security procedures, "
echo -e "\033[33;3msurvivability and operational security. "
echo -e "\n"
echo -e "\033[33;3mAny information on this computer system may be examined, recorded "
echo -e "\033[33;3mand copied and used for authorized purposes at any time. "
echo -e "\n"
echo -e "\033[33;3mAll information, including personal information, placed or sent over "
echo -e "\033[33;3mthis system may be monitored, and users of this system are reminded "
echo -e "\033[33;3mthat such monitoring does occur. Therefore, there should be no "
echo -e "\033[33;3mexpectation of privacy with respect to use of this system. "
sleep 1
echo -e "\033[31;3m██████████████████████████████████████████████████████████████████████████████\n"
echo -e "\033[31;3mBy logging into this FTN computer system, "
echo -e "\033[31;3myou acknowledge and consent to monitoring of this system. "
echo -e "\n"
sleep 1
echo -e "\033[31;3m**Evidence of your use, authorized and unauthorized, collected during \n"
echo -e "\033[31;3mmonitoring may be used for civil, criminal, administrative, or other \n"
echo -e "\033[31;3madverse action. Unauthorized or illegal use may subject you to prosecution.** \n"
echo -e "\n"
echo -e "\033[31;3mBy using this network, you certify that you have read, understand, and "
echo -e "\033[31;3magree to abide by the Rules of Behavior for Blockchain Network Users and Warning Banner. "
echo -e "\033[31;3m██████████████████████████████████████████████████████████████████████████████\n"
